# Generated by Django 2.0.1 on 2018-10-20 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('release_date', models.DateField()),
                ('image', models.ImageField(upload_to='album_images')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='artist_images')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='playlist_images')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=250)),
                ('audio_file', models.FileField(upload_to='')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Album')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='album_songs',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='album_songs',
            name='album',
        ),
        migrations.RemoveField(
            model_name='album_songs',
            name='song',
        ),
        migrations.RemoveField(
            model_name='albums',
            name='image',
        ),
        migrations.RemoveField(
            model_name='artists',
            name='image_id',
        ),
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='song',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='performed_by',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='performed_by',
            name='album',
        ),
        migrations.RemoveField(
            model_name='performed_by',
            name='artist',
        ),
        migrations.AlterUniqueTogether(
            name='playlists',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='playlists',
            name='song',
        ),
        migrations.RemoveField(
            model_name='playlists',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='sung_by',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='sung_by',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='sung_by',
            name='song',
        ),
        migrations.DeleteModel(
            name='Album_Songs',
        ),
        migrations.DeleteModel(
            name='Albums',
        ),
        migrations.DeleteModel(
            name='Artists',
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Performed_By',
        ),
        migrations.DeleteModel(
            name='Playlists',
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
        migrations.DeleteModel(
            name='Sung_By',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='song',
            name='favorite_of',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='favorite_of',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
