# Generated by Django 2.0.1 on 2018-10-21 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_song_part_of_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='favorite_of',
            field=models.ManyToManyField(blank=True, related_name='songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='part_of_playlist',
            field=models.ManyToManyField(blank=True, related_name='songs', to='management.Playlist'),
        ),
    ]
