# Generated by Django 2.2 on 2019-04-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20190409_0156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'permissions': (('can_add_many_artists', 'Can add many artists'),)},
        ),
    ]
